services:
    user-db:
        image: postgres:15-alpine
        container_name: user-db
        environment:
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${USER}
            POSTGRES_PASSWORD: ${PASSWORD}
        ports:
            - "5433:5432"
        volumes:
            - ./db-init/user-service:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${USER_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    product-db:
        image: postgres:15-alpine
        container_name: product-db
        environment:
            POSTGRES_DB: ${PRODUCT_DB}
            POSTGRES_USER: ${USER}
            POSTGRES_PASSWORD: ${PASSWORD}
        ports:
            - "5434:5432"
        volumes:
            - ./db-init/product-service:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${PRODUCT_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    order-db:
        image: postgres:15-alpine
        container_name: order-db
        environment:
            POSTGRES_DB: ${ORDER_DB}
            POSTGRES_USER: ${USER}
            POSTGRES_PASSWORD: ${PASSWORD}
        ports:
            - "5435:5432"
        volumes:
            - ./db-init/order-service:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${ORDER_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    user-service:
        build:
            context: ./microservices/user
            dockerfile: Dockerfile
        container_name: user-service
        depends_on:
            - user-db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB}
            SPRING_DATASOURCE_USERNAME: ${USER}
            SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
            USER_DB_HOST: ${USER_DB_HOST}
            USER_DB_PORT: ${USER_DB_PORT}
        ports:
            - "8081:8081"

    product-service:
        build:
            context: ./microservices/product
            dockerfile: Dockerfile
        container_name: product-service
        depends_on:
            - product-db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://${PRODUCT_DB_HOST}:${PRODUCT_DB_PORT}/${PRODUCT_DB}
            SPRING_DATASOURCE_USERNAME: ${USER}
            SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
            PRODUCT_DB_HOST: ${PRODUCT_DB_HOST}
            PRODUCT_DB_PORT: ${PRODUCT_DB_PORT}
        ports:
            - "8082:8082"

    order-service:
        build:
            context: ./microservices/order
            dockerfile: Dockerfile
        container_name: order-service
        depends_on:
            - order-db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB}
            SPRING_DATASOURCE_USERNAME: ${USER}
            SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
            ORDER_DB_HOST: ${ORDER_DB_HOST}
            ORDER_DB_PORT: ${ORDER_DB_PORT}
            USER_SERVICE_BASE_URL: http://user-service:8081
            PRODUCT_SERVICE_BASE_URL: http://product-service:8082
        ports:
            - "8083:8083"
