apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    cloud.google.com/backend-config: '{"default":"user-backendconfig"}'
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


