name: Test Docker Compose on GitHub Actions

on:
  push:
    branches: [ci/setup-cloud]
    # Only run the workflow if the commit message contains "[deploy]"
  pull_request:
    branches: [ci/setup-cloud]

jobs:
  test:
    if: contains(github.event.head_commit.message, '[deploy]')  # Only run if commit message contains "[deploy]"
    runs-on: ubuntu-latest
    env:
      USER_DB: user_service_db
      PRODUCT_DB: product_service_db
      ORDER_DB: order_service_db

      USER: postgres
      PASSWORD: postgres

      USER_DB_PORT: 5432
      PRODUCT_DB_PORT: 5432
      ORDER_DB_PORT: 5432

      USER_DB_HOST: user-db
      PRODUCT_DB_HOST: product-db
      ORDER_DB_HOST: order-db
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Step 4: Build and start services with Docker Compose
      - name: Build and start services
        run: |
          cd app  # Navigate to the folder containing docker-compose.yml
          docker-compose -f docker-compose.yml up -d --build

      # Step 5: Verify that the containers are running (optional, to check health)
      - name: Check Docker containers
        run: |
          docker ps

      # Step 6: (Optional) Run tests here to check that services are functioning 
      # Example: curl http://localhost:8081

      # Step 7: Clean up by bringing down containers
      - name: Docker Compose Down
        run: |
          cd app  # Navigate back to the app directory
          docker-compose down
